//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacman_Game.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pacman_Game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BlueGhostC {
            get {
                object obj = ResourceManager.GetObject("BlueGhostC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueGhostD {
            get {
                object obj = ResourceManager.GetObject("BlueGhostD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueGhostL {
            get {
                object obj = ResourceManager.GetObject("BlueGhostL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueGhostR {
            get {
                object obj = ResourceManager.GetObject("BlueGhostR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueGhostU {
            get {
                object obj = ResourceManager.GetObject("BlueGhostU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cherry {
            get {
                object obj = ResourceManager.GetObject("Cherry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dot {
            get {
                object obj = ResourceManager.GetObject("Dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenGhostC {
            get {
                object obj = ResourceManager.GetObject("GreenGhostC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenGhostD {
            get {
                object obj = ResourceManager.GetObject("GreenGhostD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenGhostL {
            get {
                object obj = ResourceManager.GetObject("GreenGhostL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenGhostR {
            get {
                object obj = ResourceManager.GetObject("GreenGhostR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenGhostU {
            get {
                object obj = ResourceManager.GetObject("GreenGhostU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Helppic1 {
            get {
                object obj = ResourceManager.GetObject("Helppic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Helppic2 {
            get {
                object obj = ResourceManager.GetObject("Helppic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap keyboard_arrows {
            get {
                object obj = ResourceManager.GetObject("keyboard_arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mapedit {
            get {
                object obj = ResourceManager.GetObject("Mapedit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pacman_skull {
            get {
                object obj = ResourceManager.GetObject("pacman_skull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PacmanDown {
            get {
                object obj = ResourceManager.GetObject("PacmanDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PacmanLeft {
            get {
                object obj = ResourceManager.GetObject("PacmanLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PacmanRight {
            get {
                object obj = ResourceManager.GetObject("PacmanRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PacmanUp {
            get {
                object obj = ResourceManager.GetObject("PacmanUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Points {
            get {
                object obj = ResourceManager.GetObject("Points", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurpleGhostC {
            get {
                object obj = ResourceManager.GetObject("PurpleGhostC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurpleGhostD {
            get {
                object obj = ResourceManager.GetObject("PurpleGhostD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurpleGhostL {
            get {
                object obj = ResourceManager.GetObject("PurpleGhostL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurpleGhostR {
            get {
                object obj = ResourceManager.GetObject("PurpleGhostR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurpleGhostU {
            get {
                object obj = ResourceManager.GetObject("PurpleGhostU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedGhostC {
            get {
                object obj = ResourceManager.GetObject("RedGhostC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedGhostD {
            get {
                object obj = ResourceManager.GetObject("RedGhostD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedGhostL {
            get {
                object obj = ResourceManager.GetObject("RedGhostL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedGhostR {
            get {
                object obj = ResourceManager.GetObject("RedGhostR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedGhostU {
            get {
                object obj = ResourceManager.GetObject("RedGhostU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SuperDot {
            get {
                object obj = ResourceManager.GetObject("SuperDot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TheBlueGhost {
            get {
                object obj = ResourceManager.GetObject("TheBlueGhost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowGhostC {
            get {
                object obj = ResourceManager.GetObject("YellowGhostC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowGhostD {
            get {
                object obj = ResourceManager.GetObject("YellowGhostD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowGhostL {
            get {
                object obj = ResourceManager.GetObject("YellowGhostL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowGhostR {
            get {
                object obj = ResourceManager.GetObject("YellowGhostR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowGhostU {
            get {
                object obj = ResourceManager.GetObject("YellowGhostU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
